### ISSUE TITLE
发布线上 bug

### ISSUE THREAD

**Issue by echo0110** [YYJeffrey/july_client#13]
二维码真机调试的时候  可以微信授权登陆成功

但是发布到线上后，一直无法微信授权

**Comment by YYJeffrey** [comment]
看下域名配置是否正确，无法授权有什么提示吗？请求返回了什么？

**Comment by echo0110** [comment]
你说的域名是代码哪里的配置？  没看到你说明中有说 要配置域名啊

下图是无法授权console 打印的log
![error log](https://user-images.githubusercontent.com/24950840/213991501-b542c00b-8080-4adf-baf8-6fe4b4f70ebe.png)

**Comment by echo0110** [comment]
好的 我先试下 多谢你的回答

**Comment by YYJeffrey** [comment]
嗯 不客气
