### ISSUE TITLE
无法创建树洞话题

### ISSUE THREAD

**Issue by echo0110** [YYJeffrey/july_client#14]
你好！  麻烦问下  为什么拉取的你的源码 运行后  树洞那一栏  没有创建树洞话题的按钮  

![image](https://user-images.githubusercontent.com/24950840/216626677-c4034bfb-b625-4e13-b301-bdad1ba3cea1.png)

**Comment by YYJeffrey** [comment]
你好，客户端页面是没有创建按钮的，这需要在后台管理系统中创建后在客户端刷新即可。
