### ISSUE TITLE
管理平台 忘记AppSecret

### ISSUE THREAD

**Issue by echo0110** [YYJeffrey/july_client#15]
管理平台 忘记AppSecret   该怎么找回啊

**Comment by YYJeffrey** [comment]
你好，这个是无法主动找回的，如果方便可以发我一下APP ID和注册时所留的邮箱，回头我发回你的邮箱

**Comment by echo0110** [comment]
APPID：   wx97d10bfda0c0b363


***@***.***


上面是注册时的appid 和邮箱  
多谢了 





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "YYJeffrey/july_client"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月4日(星期六) 下午2:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [YYJeffrey/july_client] 管理平台 忘记AppSecret (Issue #15)





 
你好，这个是无法主动找回的，如果方便可以发我一下APP ID和注册时所留的邮箱，回头我发回你的邮箱

**Comment by echo0110** [comment]
你好 ， 麻烦有空的话 帮忙找下我的&nbsp;&nbsp;AppSecret。
多谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "花开彼岸"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月4日(星期六) 下午2:54
***@***.***&gt;;

主题:&nbsp;回复： [YYJeffrey/july_client] 管理平台 忘记AppSecret (Issue #15)



APPID：   wx97d10bfda0c0b363


***@***.***


上面是注册时的appid 和邮箱  
多谢了 





------------------ 原始邮件 ------------------
发件人:                                                                                                                        "YYJeffrey/july_client"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月4日(星期六) 下午2:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [YYJeffrey/july_client] 管理平台 忘记AppSecret (Issue #15)





 
你好，这个是无法主动找回的，如果方便可以发我一下APP ID和注册时所留的邮箱，回头我发回你的邮箱

**Comment by echo0110** [comment]
你好 我已经找到了&nbsp; 多谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "花开彼岸"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月6日(星期一) 下午2:27
***@***.***&gt;;

主题:&nbsp;回复： [YYJeffrey/july_client] 管理平台 忘记AppSecret (Issue #15)





你好 ， 麻烦有空的话 帮忙找下我的&nbsp; AppSecret。
多谢




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "花开彼岸"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月4日(星期六) 下午2:54
***@***.***&gt;;

主题:&nbsp;回复： [YYJeffrey/july_client] 管理平台 忘记AppSecret (Issue #15)



APPID：   wx97d10bfda0c0b363


***@***.***


上面是注册时的appid 和邮箱  
多谢了 





------------------ 原始邮件 ------------------
发件人:                                                                                                                        "YYJeffrey/july_client"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月4日(星期六) 下午2:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [YYJeffrey/july_client] 管理平台 忘记AppSecret (Issue #15)





 
你好，这个是无法主动找回的，如果方便可以发我一下APP ID和注册时所留的邮箱，回头我发回你的邮箱
