### ISSUE TITLE
主页 发布内容的时候 报错

### ISSUE THREAD

**Issue by echo0110** [YYJeffrey/july_client#17]
你好  主页 发布内容的时候 报错

请问是什么原因导致的

![image](https://user-images.githubusercontent.com/24950840/218294326-05145939-28a7-4fc5-9f6c-11eb8b01d4cf.png)

直接post请求api接口的topic的时候，提示如下错误，说是token无效

<img width="1430" alt="image" src="https://user-images.githubusercontent.com/24950840/218297185-f2e3ee29-0a99-48b4-b636-0061ced327d6.png">

**Comment by echo0110** [comment]
> 你好 主页 发布内容的时候 报错
> 
> 请问是什么原因导致的
> 
> ![image](https://user-images.githubusercontent.com/24950840/218294326-05145939-28a7-4fc5-9f6c-11eb8b01d4cf.png)
> 
> 直接post请求api接口的topic的时候，提示如下错误，说是token无效
> 
> <img alt="image" width="1430" src="https://user-images.githubusercontent.com/24950840/218297185-f2e3ee29-0a99-48b4-b636-0061ced327d6.png">



你好，是不是还是因为AppSecret改变了的原因，导致无法根据正确的AppSecret获取到token

**Comment by YYJeffrey** [comment]
你到这个页面了说明已经授权过了，如果是Token无效会返回授权页面的，初步怀疑是模板消息配置问题，可以把配置的模板消息删掉再试一次

**Comment by echo0110** [comment]
> 你到这个页面了说明已经授权过了，如果是Token无效会返回授权页面的，初步怀疑是模板消息配置问题，可以把配置的模板消息删掉再试一次

你好  删掉 重新调价订阅消息模板后   主页发布内容还是报错

**Comment by YYJeffrey** [comment]
network中的报错提示是什么

**Comment by echo0110** [comment]
> network中的报错提示是什么
<img width="1262" alt="image" src="https://user-images.githubusercontent.com/24950840/219950078-0d62aa23-9ea0-44f3-aa3c-be839754f2c0.png">

**Comment by YYJeffrey** [comment]
是你的appid和appsecret有误导致的 你清楚缓存授权能成功吗

**Comment by echo0110** [comment]
> 是你的appid和appsecret有误导致的 你清楚缓存授权能成功吗

可以  清除缓存  授权可以成功

**Comment by echo0110** [comment]
> 

那应该怎么办？  重新生成新得appsecret 重新注册？

**Comment by YYJeffrey** [comment]
![image](https://user-images.githubusercontent.com/25133698/220229774-305e2077-b88a-430c-8fa1-fad9490c9c78.png)
这两个模板删掉试过了吗？还是不能发布吗？

**Comment by echo0110** [comment]
> ![image](https://user-images.githubusercontent.com/25133698/220229774-305e2077-b88a-430c-8fa1-fad9490c9c78.png) 这两个模板删掉试过了吗？还是不能发布吗？

你好，不能。删掉后  再试  还是那个报错

**Comment by YYJeffrey** [comment]
你后续是不是又重新修改了appsecret？

**Comment by echo0110** [comment]
> 你后续是不是又重新修改了appsecret？

没有啊   就是上次的deabdc54f824a31a871c43002cb56396  啊

**Comment by echo0110** [comment]
> 你后续是不是又重新修改了appsecret？
你好 ，  要不帮忙给我的APPID  给注销掉   我重新注册一下？

**Comment by YYJeffrey** [comment]
后续我把你的数据都删掉 你在注册试试

**Comment by echo0110** [comment]
> 后续我把你的数据都删掉 你在注册试试


嗯嗯 好的  多谢了啊

**Comment by echo0110** [comment]
> > 后续我把你的数据都删掉 你在注册试试
> 
> 嗯嗯 好的 多谢了啊

你好，  麻烦  后面数据删掉以后     告知我一下

**Comment by YYJeffrey** [comment]
已清除了你平台的所有数据 再试试吧 如果还不行就没办法了

**Comment by echo0110** [comment]
> 已清除了你平台的所有数据 再试试吧 如果还不行就没办法了

你好 ，重新注册后，连授权都授权不了的
<img width="1439" alt="WechatIMG471" src="https://user-images.githubusercontent.com/24950840/220901992-7bc1bcb3-026e-4277-8e8c-b5fb08e82881.png">

**Comment by YYJeffrey** [comment]
清空缓存后执行的吗 具体的传参发一下

**Comment by echo0110** [comment]
> 清空缓存后执行的吗 具体的传参发一下

你好，现在可以了，我自己可以授权通过，然后也可以主页发布消息了。

但是我上传了一个体验版，别人用的话。就无法授权  可能是什么原因呢？

**Comment by YYJeffrey** [comment]
建议看看调试信息

**Comment by echo0110** [comment]
> 建议看看调试信息

看不到调试信息啊   二维码真机调试的时候， 别人的手机扫的话  直接就是提示 没有访问权限

**Comment by echo0110** [comment]
> > 建议看看调试信息
> 
> 看不到调试信息啊 二维码真机调试的时候， 别人的手机扫的话 直接就是提示 没有访问权限

![image](https://user-images.githubusercontent.com/24950840/224462938-39657ff8-194b-493e-b31c-0590d4e6e9f9.png)


![image](https://user-images.githubusercontent.com/24950840/224462948-3941a211-345f-4101-a86a-dcce3488bcad.png)

**Comment by echo0110** [comment]
![image](https://user-images.githubusercontent.com/24950840/226090391-7d7a1b87-61ac-44fb-8041-d73aaae30f57.png)

你好，感觉 是我这边post请求后，后台解密post的请求 出了问题，导致解密的结果错误值返回了500

**Comment by YYJeffrey** [comment]
能否把请求拦截下来的参数发我一下

**Comment by YYJeffrey** [comment]
> Author

目前可以知道的原因是日志显示 你的 AppId与 AppSecret 不一致，所以我这边也没办法

**Comment by echo0110** [comment]
> > Author
> 
> 目前可以知道的原因是日志显示 你的 AppId与 AppSecret 不一致，所以我这边也没办法

这是别人授权的时候，报 的错误。  但是我自己去授权的话 是没问题的

**Comment by echo0110** [comment]
> AppId与 AppSecret 不

无论是我扫码post授权验证请求，还是别人扫码post请求授权验证，  我所理解的是后台不应该都是去验证我的appid  和appscecret吗?    按理说既然我自己扫码post授权验证请求可以通过，那么按理说我的appid 和appsecret应该是没问题吧？

**Comment by echo0110** [comment]
> > Author
> 
> 目前可以知道的原因是日志显示 你的 AppId与 AppSecret 不一致，所以我这边也没办法

你的意思是说 我这边前端请求传的appsecret  和你后台看到的不一致吗？

**Comment by YYJeffrey** [comment]
> 

我的意思是 你微信小程序后台的 Secret 和 七月管理系统后台的不一致
只有授权的时候需要 AppSecret 成功之后是不需要的

**Comment by echo0110** [comment]
> > 
> 
> 我的意思是 你微信小程序后台的 Secret 和 七月管理系统后台的不一致 只有授权的时候需要 AppSecret 成功之后是不需要的

那麻烦你可以把的账号给注销删除掉吗？  我再重新注册一下

**Comment by YYJeffrey** [comment]
等后续在弄吧 这几天服务器要维护 需要关掉一段时间

**Comment by echo0110** [comment]
> 等后续在弄吧 这几天服务器要维护 需要关掉一段时间

好的 多谢了

**Comment by echo0110** [comment]
> 等后续在弄吧 这几天服务器要维护 需要关掉一段时间

你好，麻烦问下 现在服务器是什么情况？  有空的话麻烦帮忙把我的账户给注销删除一下。多谢

**Comment by YYJeffrey** [comment]
你把最新的 AppSecret 发我邮箱

**Comment by echo0110** [comment]
你好，最新的appscret:


cf9b345cabbe0f8b3e299737c1dfad98





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "YYJeffrey/july_client"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月28日(星期二) 晚上8:00
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [YYJeffrey/july_client] 主页 发布内容的时候 报错 (Issue #17)





 
你把最新的 AppSecret 发我邮箱

**Comment by echo0110** [comment]
> 你把最新的 AppSecret 发我邮箱

你好，已发送

**Comment by YYJeffrey** [comment]
appid也发我一下
&nbsp;


Patron&nbsp;Saint
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月28日(星期二) 晚上8:06
收件人: ***@***.***&gt;; 
抄送: "Patron ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [YYJeffrey/july_client] 主页 发布内容的时候 报错 (Issue #17)





  
你把最新的 AppSecret 发我邮箱
  
你好，已发送

**Comment by echo0110** [comment]
你好，
appid :&nbsp;wx97d10bfda0c0b363


AppSecret :cf9b345cabbe0f8b3e299737c1dfad98
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "YYJeffrey/july_client"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月28日(星期二) 晚上8:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [YYJeffrey/july_client] 主页 发布内容的时候 报错 (Issue #17)





 appid也发我一下 
 &amp;nbsp; 
 
 
 Patron&amp;nbsp;Saint 
 ***@***.*** 
 
 
 
 &amp;nbsp; 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人: ***@***.***&amp;gt;;  
 发送时间: 2023年3月28日(星期二) 晚上8:06 
 收件人: ***@***.***&amp;gt;;  
 抄送: "Patron ***@***.***&amp;gt;; "State ***@***.***&amp;gt;;  
 主题: Re: [YYJeffrey/july_client] 主页 发布内容的时候 报错 (Issue #17) 
 
 
 
 
 
    
 你把最新的 AppSecret 发我邮箱 
    
 你好，已发送

**Comment by echo0110** [comment]
你好，我是可以直接试？&nbsp; 不需要重新注册一遍了？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "YYJeffrey/july_client"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月28日(星期二) 晚上8:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [YYJeffrey/july_client] 主页 发布内容的时候 报错 (Issue #17)





 
好了 你再试下之前授权的问题看看

**Comment by echo0110** [comment]
还是无法授权啊


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "YYJeffrey/july_client"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月28日(星期二) 晚上8:13
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [YYJeffrey/july_client] 主页 发布内容的时候 报错 (Issue #17)





 
不需要 登录后台的话 还是用之前的密码

**Comment by echo0110** [comment]
下图是Network日志



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "YYJeffrey/july_client"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月28日(星期二) 晚上8:26
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [YYJeffrey/july_client] 主页 发布内容的时候 报错 (Issue #17)





 
network 日志有吗

**Comment by YYJeffrey** [comment]
我这里看不到你发的图片 把请求的信息 和 返回的信息都截图下来看看

**Comment by echo0110** [comment]
> 我这里看不到你发的图片 把请求的信息 和 返回的信息都截图下来看看


![image](https://user-images.githubusercontent.com/24950840/228724107-19a7770a-7a6a-4c13-af53-1f7349b1345e.png)

**Comment by YYJeffrey** [comment]
加你Q了 通过一下 谢谢

**Comment by echo0110** [comment]
你是加的&nbsp;820713556&nbsp; &nbsp;这个吗？
你加这个&nbsp;&nbsp;820713556&nbsp; 吧




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "YYJeffrey/july_client"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月30日(星期四) 中午12:06
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [YYJeffrey/july_client] 主页 发布内容的时候 报错 (Issue #17)





 
加你Q了 通过一下 谢谢
