### ISSUE TITLE
您好，想请教一下，API文档的注册接口，为什么注册后返回“Token Invalid, Please Contact Administrator"

### ISSUE THREAD

**Issue by Xlight5** [YYJeffrey/july_client#18]
您好！我想请教一下，为什么我请求七月管理后台API的注册接口后，他返回的是
{
  "code": 400,
  "message": "Token Invalid, Please Contact Administrator"
}
想问一下解决方法，谢谢！

**Comment by YYJeffrey** [comment]
重新在试一下看
